# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ca635b6a1f71c19fb0d30c03e4f808bf19ad822dc70d34f13505eb39f2f3c8e0bc3e54046cba9de60b06aa344136e902a604534269454c02f9bd132eeed848

test:
  secret_key_base: 45398a8f4d7aff74925421e9b754fe607b5764b60d136b364c9928b0c8a86ad461da7f0c5538ba2fbf06f0bba30b17037db16a8e288271a9318ad88c4f946f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
